=== falquaddoomi/cens_dev/taskmanager/scripts/xmltask.dtd
<?xml version="1.0"?>

<!ELEMENT interaction (message*,response*)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT response (message*,link*,response*)>
<!ELEMENT link (EMPTY)>

<!ATTLIST interaction id CDATA #IMPLIED>
<!ATTLIST response id CDATA #IMPLIED>
<!ATTLIST response pattern CDATA #REQUIRED>
<!ATTLIST link target CDATA #REQUIRED>

=== falquaddoomi/cens_dev/taskmanager/scripts/greeter.xml
<?xml version="1.0"?>
<!DOCTYPE interaction SYSTEM "xmltask.dtd">

<interaction id="toplevel">
	<message>
	Hey, {{ patient.first_name }}! How are you doing?
	</message>
	
	<response pattern="good">
		<message>
		That's great to hear!
		</message>
	</response>
	
	<response pattern="(?P{@cond@}bad|poor|lonely)">
		<message>
		Aww, what's wrong? Why are you {{ match.cond }}?
		</message>
		
		<response pattern=".+">
			<message>Well, I hope you feel better soon!</message>
		</response>
	</response>
	
	<response pattern=".*">
		<message>
		Sorry, I couldn't understand your input ({{ message }}), but try again next time perhaps...
		</message>
		
		<link target="toplevel" />
	</response>
</interaction>

=== falquaddoomi/cens_dev/taskmanager/tasks/scripts/tests/greeter.xml
<?xml version="1.0"?>
<!DOCTYPE interaction SYSTEM "xmltask.dtd">

<interaction id="toplevel" prefix="greet">
	<message>
	Hey, {{ patient.first_name }}! How are you doing?
	</message>
	
	<store key="his_last_name" value="{{ patient.last_name }}" />
	
	<response pattern="good">
		<message>
		That's great to hear!
		</message>
	</response>
	
	<response pattern="(?P{@cond@}bad|poor|lonely)">
		<message>
		Aww, what's wrong? Why are you {{ match.cond }}?
		</message>
		
		<response pattern=".+">
			<message>Well, I hope you feel better soon!</message>
			
			<store key="last_response" value="{{ message }}" />
		</response>
	</response>
	
	<response pattern=".*">
		<message>
		Sorry, I couldn't understand your input; try again?
		</message>
		
		<link target="toplevel" />
	</response>
	
	<timeout duration="in 1 minute">
		<message>
		Hey, are you there, {{ patient.first_name }}?
		</message>
		
		<link target="toplevel" />
	</timeout>
</interaction>

=== falquaddoomi/cens_dev/taskmanager/tasks/scripts/tests/appt_request.xml
<?xml version="1.0"?>
<!DOCTYPE interaction SYSTEM "xmltask.dtd">

<interaction id="toplevel" prefix="appt">
	<message>
	Hi, {{ patient.first_name }}. You need to schedule a blood test. After you have done so,
	text back the date and time of your test.
	</message>
	
	<response type="date_time" id="requesting_appt">
		<message>
		{% load parse_date %}
		Ur appt is {{ parsed_datetime|relative_date }}. Is this correct? If so, text back "ok". If not, text back date & time again.
		</message>

		<store name="appt_pending" value="{{ parsed_datetime }}" />

		<response pattern="ok">
			<message>
			Thank you. You will be reminded shortly before your appointment.
			</message>

			<schedule task="ex_appt_reminder" date="{{ parsed_datetime }}" offset="1 minute before" />
		</response>

		<response type="date_time">
			<link target="requesting_appt" />
		</response>
	</response>
</interaction>
